name: build-docs
on:
  workflow_call:
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: docs
      - name: Checkout docs-builder
        uses: actions/checkout@v4
        with:
          repository: envicutor/docs-builder
          path: docs-builder
      - name: Run `make build`
        run: make build path="$GITHUB_WORKSPACE/docs"
        working-directory: ${{ github.workspace }}/docs-builder
        shell: bash
      - name: Upload HTML artifact
        uses: actions/upload-artifact@v3
        with:
          name: html
          path: ${{ github.workspace }}/docs/_build/html
