name: Common workflow
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      branch-name:
        required: true
        type: string
    secrets:
      pat:
        required: true
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: docs
      - name: Checkout docs-builder
        uses: actions/checkout@v4
        with:
          repository: envicutor/docs-builder
          path: docs-builder
      - name: Run `make build`
        run: make build path="$GITHUB_WORKSPACE/docs"
        working-directory: ${{ github.workspace }}/docs-builder
        shell: bash
      - name: Push HTML to built docs repo
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.pat }}
        with:
          source-directory: docs/_build/html
          destination-github-username: 'envicutor'
          destination-repository-name: ${{ inputs.target }}
          target-branch: ${{ inputs.branch-name }}
          user-name: github-actions[bot]
          user-email: 41898282+github-actions[bot]@users.noreply.github.com
          create-target-branch-if-needed: true
