name: Deploy website to main
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
    secrets:
      pat:
        required: true
jobs:
  run-deploy-to-branch:
    uses: envicutor/docs-workflows/.github/workflows/deploy-branch.yml@main
    with:
      target: ${{ inputs.target }}
      branch-name: main
    secrets:
      pat: ${{ secrets.pat }}
