name: Build and deploy docs
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
    secrets:
      pat:
        required: true
jobs:
  build-docs:
    uses: envicutor/docs-workflows/.github/workflows/common.yml@main
  deploy:
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Download HTML
        uses: actions/download-artifact@v3
        with:
          name: html
          path: ${{ github.workspace }}/html
      - name: Checkout deploy
        uses: actions/checkout@v4
        with:
          ref: deploy
          path: deploy
      - name: Deploy html
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.pat }}
        with:
          source-directory: ${{ github.workspace }}/html
          destination-github-username: 'envicutor'
          destination-repository-name: ${{ inputs.target }}
          user-name: github-actions[bot]
          user-email: 41898282+github-actions[bot]@users.noreply.github.com
