name: After pushing to main (abstract)
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
    secrets:
      pat:
        required: true
jobs:
  run-common-workflow:
    uses: envicutor/docs-workflows/.github/workflows/common.yml@main
    with:
      target: ${{ inputs.target }}
      branch-name: main
    secrets:
      pat: ${{ secrets.pat }}
