name: On pull request (abstract)
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
    secrets:
      pat:
        required: true
env:
  BRANCH_NAME: pr-${{ github.event.number }}
jobs:
  run-deploy-to-branch-workflow:
    uses: envicutor/docs-workflows/.github/workflows/deploy-branch.yml@main
    with:
      target: ${{ inputs.target }}
      # We can't seem to use env here: https://github.com/actions/runner/issues/1189#issuecomment-1741672276
      branch-name: pr-${{ github.event.number }}
    secrets:
      pat: ${{ secrets.pat }}
  comment-on-pr:
    needs: run-deploy-to-branch-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2.4.2
        with:
          message: |
            A preview build has been pushed to
            https://github.com/envicutor/${{ inputs.target }}/tree/${{ env.BRANCH_NAME }}
